### ISSUE TITLE
Find switch-like genes on existing pseudotime

### ISSUE THREAD

**Issue by charliex210** [kieranrcampbell/ouija#5]
Hello,
Can I fit the model and find the switch-like genes based on existing pseudotime defined by other methods?
Thanks!

**Comment by kieranrcampbell** [comment]
Yes, we have a method called switchde for this. 

R package - https://bioconductor.org/packages/release/bioc/html/switchde.html

Paper - https://academic.oup.com/bioinformatics/article/33/8/1241/2736366

Let me know if you have any more questions.
